# Generated by Django 3.2.3 on 2021-05-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_links_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Content',
        ),
    ]
